name: Build for macOS and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the macOS app
      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name TaskManager \
            --add-data "models.py:." \
            --add-data "styles.py:." \
            --add-data "database.py:." \
            --hidden-import sqlite3 ui.py

      # Step 5: Compress the macOS build
      - name: Compress macOS Build
        run: zip -r dist/TaskManager-macOS.zip dist/TaskManager.app

      # Step 6: Create GitHub Release
      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: TaskManager Release v1.0.0
          body: "TaskManager builds for macOS and Windows."
          draft: false
          prerelease: false

      # Step 7: Upload macOS Build to Release
      - name: Upload macOS Build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/TaskManager-macOS.zip
          asset_name: TaskManager-macOS.zip
          asset_content_type: application/zip

  build-windows:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the Windows executable
      - name: Build Windows executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name TaskManager \
            --add-data "models.py;." \
            --add-data "styles.py;." \
            --add-data "database.py;." \
            --hidden-import sqlite3 ui.py

      # Step 5: Create GitHub Release
      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: TaskManager Release v1.0.0
          body: "TaskManager builds for macOS and Windows."
          draft: false
          prerelease: false

      # Step 6: Upload Windows Build to Release
      - name: Upload Windows Build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/TaskManager.exe
          asset_name: TaskManager-Windows.exe
          asset_content_type: application/octet-stream
